# Generated by Django 3.1.7 on 2021-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='costumer',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='nborders',
            field=models.IntegerField(default=''),
        ),
    ]
