# Generated by Django 3.1.7 on 2021-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20210604_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostumerID', models.CharField(default='', max_length=200)),
                ('NumberOfProducts', models.CharField(max_length=200)),
                ('ProductIDs', models.CharField(default='', max_length=200)),
                ('TotalPrice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='costumer',
            name='nborders',
            field=models.IntegerField(default='0'),
        ),
    ]
