# Generated by Django 3.1.7 on 2021-06-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_auto_20210604_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CostumerID',
        ),
    ]
