# Generated by Django 3.1.7 on 2021-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_remove_cart_costumerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='CostumerID',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
