# Generated by Django 3.1.7 on 2021-06-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_auto_20210604_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostumerID', models.CharField(max_length=200)),
                ('CartID', models.CharField(max_length=200)),
                ('OrderID', models.CharField(default='', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, default='', null=True)),
                ('issue', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
