# Generated by Django 3.1.7 on 2021-06-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='issue',
            field=models.TextField(default='', max_length=500),
        ),
    ]
