# Generated by Django 3.1.7 on 2021-06-04 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0014_remove_product_providerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='providerId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainPage.provider'),
            preserve_default=False,
        ),
    ]
