# Generated by Django 3.1.7 on 2021-06-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0017_auto_20210604_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='providerId',
        ),
    ]
