# Generated by Django 3.1.7 on 2021-06-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0021_auto_20210604_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='CostumerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.costumer'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='CartID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.cart'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='CostumerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.costumer'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='CartID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='CostumerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.costumer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.provider'),
        ),
    ]
