# Generated by Django 3.1.7 on 2021-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0022_auto_20210604_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='globalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tropical Deliveries', max_length=200)),
                ('year', models.CharField(default='2021', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
